import type { Metadata } from "next";
import Header from "@/app/layout_components/header/header";
import "./globals.css";
import { Poppins, Updock } from 'next/font/google';
import Footer from "./layout_components/footer/footer";

const headingFont = Updock({
  weight: ['400'],
  subsets: ['latin'],
  variable: '--head',
});

const bodyFont = Poppins({
  weight: ['500'],
  subsets: ['latin'],
  variable: '--body',
});

// need to update meta data
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${bodyFont.className} ${headingFont.variable}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
