import type { Metadata } from "next";
import Header from "@/app/layout_components/header/header";
import "./globals.css";
import { Poppins, Updock } from 'next/font/google';
import Footer from "./layout_components/footer/footer";
import CartBadgeUpdater from "./layout_components/cart-badge-updater";
import { Toaster } from "react-hot-toast";


const headingFont = Updock({
  weight: ['400'],
  subsets: ['latin'],
  variable: '--head',
});

const bodyFont = Poppins({
  weight: ['500'],
  subsets: ['latin'],
  variable: '--body',
});

export const metadata: Metadata = {
  title: {
    default: "Handcrafted Haven",
    template: '%s | Handcrafted Haven'
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${bodyFont.className} ${headingFont.variable}`}>
        <Toaster position="top-right" />
        
        <Header />
        <CartBadgeUpdater />
        {children}
        <Footer />
      </body>
    </html>
  );
}